# Generated by Django 4.2.15 on 2024-08-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='company_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
